(cl:defpackage stage_ros-srv
  (:use )
  (:export
   "STAGEROSGETPOSES"
   "<STAGEROSGETPOSES-REQUEST>"
   "STAGEROSGETPOSES-REQUEST"
   "<STAGEROSGETPOSES-RESPONSE>"
   "STAGEROSGETPOSES-RESPONSE"
   "STAGEROSSETPOSES"
   "<STAGEROSSETPOSES-REQUEST>"
   "STAGEROSSETPOSES-REQUEST"
   "<STAGEROSSETPOSES-RESPONSE>"
   "STAGEROSSETPOSES-RESPONSE"
  ))

