// Generated by gencpp from file stage_ros/StageRosGetPosesRequest.msg
// DO NOT EDIT!


#ifndef STAGE_ROS_MESSAGE_STAGEROSGETPOSESREQUEST_H
#define STAGE_ROS_MESSAGE_STAGEROSGETPOSESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace stage_ros
{
template <class ContainerAllocator>
struct StageRosGetPosesRequest_
{
  typedef StageRosGetPosesRequest_<ContainerAllocator> Type;

  StageRosGetPosesRequest_()
    {
    }
  StageRosGetPosesRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::stage_ros::StageRosGetPosesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stage_ros::StageRosGetPosesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StageRosGetPosesRequest_

typedef ::stage_ros::StageRosGetPosesRequest_<std::allocator<void> > StageRosGetPosesRequest;

typedef boost::shared_ptr< ::stage_ros::StageRosGetPosesRequest > StageRosGetPosesRequestPtr;
typedef boost::shared_ptr< ::stage_ros::StageRosGetPosesRequest const> StageRosGetPosesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stage_ros::StageRosGetPosesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stage_ros::StageRosGetPosesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace stage_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::stage_ros::StageRosGetPosesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stage_ros::StageRosGetPosesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stage_ros::StageRosGetPosesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stage_ros::StageRosGetPosesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stage_ros::StageRosGetPosesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stage_ros::StageRosGetPosesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stage_ros::StageRosGetPosesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::stage_ros::StageRosGetPosesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::stage_ros::StageRosGetPosesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stage_ros/StageRosGetPosesRequest";
  }

  static const char* value(const ::stage_ros::StageRosGetPosesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stage_ros::StageRosGetPosesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::stage_ros::StageRosGetPosesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stage_ros::StageRosGetPosesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StageRosGetPosesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stage_ros::StageRosGetPosesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::stage_ros::StageRosGetPosesRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // STAGE_ROS_MESSAGE_STAGEROSGETPOSESREQUEST_H
