// Generated by gencpp from file stage_ros/StageRosGetPoses.msg
// DO NOT EDIT!


#ifndef STAGE_ROS_MESSAGE_STAGEROSGETPOSES_H
#define STAGE_ROS_MESSAGE_STAGEROSGETPOSES_H

#include <ros/service_traits.h>


#include <stage_ros/StageRosGetPosesRequest.h>
#include <stage_ros/StageRosGetPosesResponse.h>


namespace stage_ros
{

struct StageRosGetPoses
{

typedef StageRosGetPosesRequest Request;
typedef StageRosGetPosesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StageRosGetPoses
} // namespace stage_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::stage_ros::StageRosGetPoses > {
  static const char* value()
  {
    return "31a710d661541413a823a4591402c488";
  }

  static const char* value(const ::stage_ros::StageRosGetPoses&) { return value(); }
};

template<>
struct DataType< ::stage_ros::StageRosGetPoses > {
  static const char* value()
  {
    return "stage_ros/StageRosGetPoses";
  }

  static const char* value(const ::stage_ros::StageRosGetPoses&) { return value(); }
};


// service_traits::MD5Sum< ::stage_ros::StageRosGetPosesRequest> should match
// service_traits::MD5Sum< ::stage_ros::StageRosGetPoses >
template<>
struct MD5Sum< ::stage_ros::StageRosGetPosesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::stage_ros::StageRosGetPoses >::value();
  }
  static const char* value(const ::stage_ros::StageRosGetPosesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::stage_ros::StageRosGetPosesRequest> should match
// service_traits::DataType< ::stage_ros::StageRosGetPoses >
template<>
struct DataType< ::stage_ros::StageRosGetPosesRequest>
{
  static const char* value()
  {
    return DataType< ::stage_ros::StageRosGetPoses >::value();
  }
  static const char* value(const ::stage_ros::StageRosGetPosesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::stage_ros::StageRosGetPosesResponse> should match
// service_traits::MD5Sum< ::stage_ros::StageRosGetPoses >
template<>
struct MD5Sum< ::stage_ros::StageRosGetPosesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::stage_ros::StageRosGetPoses >::value();
  }
  static const char* value(const ::stage_ros::StageRosGetPosesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::stage_ros::StageRosGetPosesResponse> should match
// service_traits::DataType< ::stage_ros::StageRosGetPoses >
template<>
struct DataType< ::stage_ros::StageRosGetPosesResponse>
{
  static const char* value()
  {
    return DataType< ::stage_ros::StageRosGetPoses >::value();
  }
  static const char* value(const ::stage_ros::StageRosGetPosesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STAGE_ROS_MESSAGE_STAGEROSGETPOSES_H
