// Generated by gencpp from file stage_ros/StageRosSetPosesResponse.msg
// DO NOT EDIT!


#ifndef STAGE_ROS_MESSAGE_STAGEROSSETPOSESRESPONSE_H
#define STAGE_ROS_MESSAGE_STAGEROSSETPOSESRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace stage_ros
{
template <class ContainerAllocator>
struct StageRosSetPosesResponse_
{
  typedef StageRosSetPosesResponse_<ContainerAllocator> Type;

  StageRosSetPosesResponse_()
    : response(false)  {
    }
  StageRosSetPosesResponse_(const ContainerAllocator& _alloc)
    : response(false)  {
  (void)_alloc;
    }



   typedef uint8_t _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::stage_ros::StageRosSetPosesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stage_ros::StageRosSetPosesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct StageRosSetPosesResponse_

typedef ::stage_ros::StageRosSetPosesResponse_<std::allocator<void> > StageRosSetPosesResponse;

typedef boost::shared_ptr< ::stage_ros::StageRosSetPosesResponse > StageRosSetPosesResponsePtr;
typedef boost::shared_ptr< ::stage_ros::StageRosSetPosesResponse const> StageRosSetPosesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stage_ros::StageRosSetPosesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stage_ros::StageRosSetPosesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stage_ros::StageRosSetPosesResponse_<ContainerAllocator1> & lhs, const ::stage_ros::StageRosSetPosesResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stage_ros::StageRosSetPosesResponse_<ContainerAllocator1> & lhs, const ::stage_ros::StageRosSetPosesResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stage_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::stage_ros::StageRosSetPosesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stage_ros::StageRosSetPosesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stage_ros::StageRosSetPosesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stage_ros::StageRosSetPosesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stage_ros::StageRosSetPosesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stage_ros::StageRosSetPosesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stage_ros::StageRosSetPosesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "003b81baa95ab323fc1ddf3c7d0bee81";
  }

  static const char* value(const ::stage_ros::StageRosSetPosesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x003b81baa95ab323ULL;
  static const uint64_t static_value2 = 0xfc1ddf3c7d0bee81ULL;
};

template<class ContainerAllocator>
struct DataType< ::stage_ros::StageRosSetPosesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stage_ros/StageRosSetPosesResponse";
  }

  static const char* value(const ::stage_ros::StageRosSetPosesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stage_ros::StageRosSetPosesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool response\n"
;
  }

  static const char* value(const ::stage_ros::StageRosSetPosesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stage_ros::StageRosSetPosesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StageRosSetPosesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stage_ros::StageRosSetPosesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stage_ros::StageRosSetPosesResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STAGE_ROS_MESSAGE_STAGEROSSETPOSESRESPONSE_H
