// Generated by gencpp from file automni_resolution/mazeActionResult.msg
// DO NOT EDIT!


#ifndef AUTOMNI_RESOLUTION_MESSAGE_MAZEACTIONRESULT_H
#define AUTOMNI_RESOLUTION_MESSAGE_MAZEACTIONRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace automni_resolution
{
template <class ContainerAllocator>
struct mazeActionResult_
{
  typedef mazeActionResult_<ContainerAllocator> Type;

  mazeActionResult_()
    : result()  {
    }
  mazeActionResult_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::automni_resolution::mazeActionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::automni_resolution::mazeActionResult_<ContainerAllocator> const> ConstPtr;

}; // struct mazeActionResult_

typedef ::automni_resolution::mazeActionResult_<std::allocator<void> > mazeActionResult;

typedef boost::shared_ptr< ::automni_resolution::mazeActionResult > mazeActionResultPtr;
typedef boost::shared_ptr< ::automni_resolution::mazeActionResult const> mazeActionResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::automni_resolution::mazeActionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::automni_resolution::mazeActionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::automni_resolution::mazeActionResult_<ContainerAllocator1> & lhs, const ::automni_resolution::mazeActionResult_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::automni_resolution::mazeActionResult_<ContainerAllocator1> & lhs, const ::automni_resolution::mazeActionResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace automni_resolution

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::automni_resolution::mazeActionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::automni_resolution::mazeActionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::automni_resolution::mazeActionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::automni_resolution::mazeActionResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::automni_resolution::mazeActionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::automni_resolution::mazeActionResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::automni_resolution::mazeActionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::automni_resolution::mazeActionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::automni_resolution::mazeActionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "automni_resolution/mazeActionResult";
  }

  static const char* value(const ::automni_resolution::mazeActionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::automni_resolution::mazeActionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"string result\n"
;
  }

  static const char* value(const ::automni_resolution::mazeActionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::automni_resolution::mazeActionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mazeActionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::automni_resolution::mazeActionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::automni_resolution::mazeActionResult_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOMNI_RESOLUTION_MESSAGE_MAZEACTIONRESULT_H
