// Generated by gencpp from file automni_resolution/mazeActionGoal.msg
// DO NOT EDIT!


#ifndef AUTOMNI_RESOLUTION_MESSAGE_MAZEACTIONGOAL_H
#define AUTOMNI_RESOLUTION_MESSAGE_MAZEACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace automni_resolution
{
template <class ContainerAllocator>
struct mazeActionGoal_
{
  typedef mazeActionGoal_<ContainerAllocator> Type;

  mazeActionGoal_()
    : technique()  {
    }
  mazeActionGoal_(const ContainerAllocator& _alloc)
    : technique(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _technique_type;
  _technique_type technique;





  typedef boost::shared_ptr< ::automni_resolution::mazeActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::automni_resolution::mazeActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct mazeActionGoal_

typedef ::automni_resolution::mazeActionGoal_<std::allocator<void> > mazeActionGoal;

typedef boost::shared_ptr< ::automni_resolution::mazeActionGoal > mazeActionGoalPtr;
typedef boost::shared_ptr< ::automni_resolution::mazeActionGoal const> mazeActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::automni_resolution::mazeActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::automni_resolution::mazeActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::automni_resolution::mazeActionGoal_<ContainerAllocator1> & lhs, const ::automni_resolution::mazeActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.technique == rhs.technique;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::automni_resolution::mazeActionGoal_<ContainerAllocator1> & lhs, const ::automni_resolution::mazeActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace automni_resolution

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::automni_resolution::mazeActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::automni_resolution::mazeActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::automni_resolution::mazeActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::automni_resolution::mazeActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::automni_resolution::mazeActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::automni_resolution::mazeActionGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::automni_resolution::mazeActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e499e08e440a0530c071297a67eb6e79";
  }

  static const char* value(const ::automni_resolution::mazeActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe499e08e440a0530ULL;
  static const uint64_t static_value2 = 0xc071297a67eb6e79ULL;
};

template<class ContainerAllocator>
struct DataType< ::automni_resolution::mazeActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "automni_resolution/mazeActionGoal";
  }

  static const char* value(const ::automni_resolution::mazeActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::automni_resolution::mazeActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"string technique\n"
;
  }

  static const char* value(const ::automni_resolution::mazeActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::automni_resolution::mazeActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.technique);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mazeActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::automni_resolution::mazeActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::automni_resolution::mazeActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "technique: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.technique);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOMNI_RESOLUTION_MESSAGE_MAZEACTIONGOAL_H
