// Auto-generated. Do not edit!

// (in-package automni_resolution.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class mazeActionFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.odom = null;
      this.collision = null;
    }
    else {
      if (initObj.hasOwnProperty('odom')) {
        this.odom = initObj.odom
      }
      else {
        this.odom = 0.0;
      }
      if (initObj.hasOwnProperty('collision')) {
        this.collision = initObj.collision
      }
      else {
        this.collision = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type mazeActionFeedback
    // Serialize message field [odom]
    bufferOffset = _serializer.float32(obj.odom, buffer, bufferOffset);
    // Serialize message field [collision]
    bufferOffset = _serializer.string(obj.collision, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type mazeActionFeedback
    let len;
    let data = new mazeActionFeedback(null);
    // Deserialize message field [odom]
    data.odom = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [collision]
    data.collision = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += _getByteLength(object.collision);
    return length + 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'automni_resolution/mazeActionFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '0bbabaecdceea6b492fa159f158a70d0';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback
    float32 odom
    string collision
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new mazeActionFeedback(null);
    if (msg.odom !== undefined) {
      resolved.odom = msg.odom;
    }
    else {
      resolved.odom = 0.0
    }

    if (msg.collision !== undefined) {
      resolved.collision = msg.collision;
    }
    else {
      resolved.collision = ''
    }

    return resolved;
    }
};

module.exports = mazeActionFeedback;
