(cl:defpackage automni_resolution-msg
  (:use )
  (:export
   "<MAZEACTION>"
   "MAZEACTION"
   "<MAZEACTIONACTION>"
   "MAZEACTIONACTION"
   "<MAZEACTIONACTIONFEEDBACK>"
   "MAZEACTIONACTIONFEEDBACK"
   "<MAZEACTIONACTIONGOAL>"
   "MAZEACTIONACTIONGOAL"
   "<MAZEACTIONACTIONRESULT>"
   "MAZEACTIONACTIONRESULT"
   "<MAZEACTIONFEEDBACK>"
   "MAZEACTIONFEEDBACK"
   "<MAZEACTIONGOAL>"
   "MAZEACTIONGOAL"
   "<MAZEACTIONRESULT>"
   "MAZEACTIONRESULT"
   "<MAZEFEEDBACK>"
   "MAZEFEEDBACK"
   "<MAZEGOAL>"
   "MAZEGOAL"
   "<MAZERESULT>"
   "MAZERESULT"
  ))

