; Auto-generated. Do not edit!


(cl:in-package automni_resolution-msg)


;//! \htmlinclude mazeActionGoal.msg.html

(cl:defclass <mazeActionGoal> (roslisp-msg-protocol:ros-message)
  ((technique
    :reader technique
    :initarg :technique
    :type cl:string
    :initform ""))
)

(cl:defclass mazeActionGoal (<mazeActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <mazeActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'mazeActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name automni_resolution-msg:<mazeActionGoal> is deprecated: use automni_resolution-msg:mazeActionGoal instead.")))

(cl:ensure-generic-function 'technique-val :lambda-list '(m))
(cl:defmethod technique-val ((m <mazeActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader automni_resolution-msg:technique-val is deprecated.  Use automni_resolution-msg:technique instead.")
  (technique m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <mazeActionGoal>) ostream)
  "Serializes a message object of type '<mazeActionGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'technique))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'technique))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <mazeActionGoal>) istream)
  "Deserializes a message object of type '<mazeActionGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'technique) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'technique) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<mazeActionGoal>)))
  "Returns string type for a message object of type '<mazeActionGoal>"
  "automni_resolution/mazeActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'mazeActionGoal)))
  "Returns string type for a message object of type 'mazeActionGoal"
  "automni_resolution/mazeActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<mazeActionGoal>)))
  "Returns md5sum for a message object of type '<mazeActionGoal>"
  "e499e08e440a0530c071297a67eb6e79")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'mazeActionGoal)))
  "Returns md5sum for a message object of type 'mazeActionGoal"
  "e499e08e440a0530c071297a67eb6e79")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<mazeActionGoal>)))
  "Returns full string definition for message of type '<mazeActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%string technique~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'mazeActionGoal)))
  "Returns full string definition for message of type 'mazeActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%string technique~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <mazeActionGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'technique))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <mazeActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'mazeActionGoal
    (cl:cons ':technique (technique msg))
))
