; Auto-generated. Do not edit!


(cl:in-package automni_resolution-msg)


;//! \htmlinclude mazeActionFeedback.msg.html

(cl:defclass <mazeActionFeedback> (roslisp-msg-protocol:ros-message)
  ((odom
    :reader odom
    :initarg :odom
    :type cl:float
    :initform 0.0)
   (collision
    :reader collision
    :initarg :collision
    :type cl:string
    :initform ""))
)

(cl:defclass mazeActionFeedback (<mazeActionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <mazeActionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'mazeActionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name automni_resolution-msg:<mazeActionFeedback> is deprecated: use automni_resolution-msg:mazeActionFeedback instead.")))

(cl:ensure-generic-function 'odom-val :lambda-list '(m))
(cl:defmethod odom-val ((m <mazeActionFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader automni_resolution-msg:odom-val is deprecated.  Use automni_resolution-msg:odom instead.")
  (odom m))

(cl:ensure-generic-function 'collision-val :lambda-list '(m))
(cl:defmethod collision-val ((m <mazeActionFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader automni_resolution-msg:collision-val is deprecated.  Use automni_resolution-msg:collision instead.")
  (collision m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <mazeActionFeedback>) ostream)
  "Serializes a message object of type '<mazeActionFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'odom))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'collision))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'collision))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <mazeActionFeedback>) istream)
  "Deserializes a message object of type '<mazeActionFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'odom) (roslisp-utils:decode-single-float-bits bits)))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'collision) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'collision) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<mazeActionFeedback>)))
  "Returns string type for a message object of type '<mazeActionFeedback>"
  "automni_resolution/mazeActionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'mazeActionFeedback)))
  "Returns string type for a message object of type 'mazeActionFeedback"
  "automni_resolution/mazeActionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<mazeActionFeedback>)))
  "Returns md5sum for a message object of type '<mazeActionFeedback>"
  "0bbabaecdceea6b492fa159f158a70d0")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'mazeActionFeedback)))
  "Returns md5sum for a message object of type 'mazeActionFeedback"
  "0bbabaecdceea6b492fa159f158a70d0")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<mazeActionFeedback>)))
  "Returns full string definition for message of type '<mazeActionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 odom~%string collision~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'mazeActionFeedback)))
  "Returns full string definition for message of type 'mazeActionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 odom~%string collision~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <mazeActionFeedback>))
  (cl:+ 0
     4
     4 (cl:length (cl:slot-value msg 'collision))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <mazeActionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'mazeActionFeedback
    (cl:cons ':odom (odom msg))
    (cl:cons ':collision (collision msg))
))
